{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "09cfa419-12a6-445d-9bc7-6ec372cae3c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-28 16:57:29.679 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-28 16:57:29.680 No runtime found, using MemoryCacheStorageManager\n",
      "2026-04-28 16:57:29.681 No runtime found, using MemoryCacheStorageManager\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAeEAAAH5CAYAAAC2z4b4AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAABB50lEQVR4nO3dd3xUVd4G8OeWyaSHFAglEEoghF4VIaCAouBKcWWxrAJWwLXuurZVQMXGuq+4+y42mrsWZF2aAuoK7xJQlCoqBBJKJJRAEkIqydx7z/tHYEwgIQkkOTP3Pt/Px49MZu7M795J5plz7jnnKkIIASIiImp0quwCiIiInIohTEREJAlDmIiISBKGMBERkSQMYSIiIkkYwkRERJIwhImIiCRhCBMREUnCECYiIpKEIUzkY2bMmAFFUaAoCtq2bSu7HADAwoULvTUpilLpvquuusr780mTJskp8By+WBNRVRjCdNFycnLw5z//Gddeey1atmyJoKAghIeHo1OnTrjqqqswY8YMfPfdd3DayqgVQ1RRFKiqCrfbjejoaHTp0gU33ngj3nnnHRQVFTV4LRXrWLhwYYO/XmNgwJKd6LILIP80b948PPzwwygsLKz089OnT6OgoABpaWn473//i5kzZ+LAgQM+06KTQQiBsrIy5ObmIjc3F7t378bSpUvx5JNPYsGCBbjhhhsqPX7EiBEIDQ0FAERERMgo+Tz9+/fH7NmzZZdRa1OnTsWvfvUrAEC3bt0kV0NUPYYw1dn//M//4NFHH/XeVhQFQ4cOxeWXX47w8HDk5ubi+++/R0pKCkpKSiRWemEFBQUICwtr8Nd56qmnEBERgRMnTiAlJQXffvstgPKehDFjxmDx4sUYP3689/EDBw7EwIEDG7yu2jh7jLp27YquXbvKLqfWJkyYILsEotoRRHWwe/duoeu6ACAAiJiYGPHNN99U+diioiLx9ttvixMnTpx337Zt28SkSZNEu3bthNvtFqGhoaJfv37itddeEyUlJec9/uzrARALFiwQq1evFoMHDxbBwcEiIiJCjBs3Thw8eLDSNuvWrau03d69e8Xzzz8vOnbsKFwul5g4caL3sYZhiIULF4rhw4eLmJgYoeu6aNq0qRg9erRYu3ZtnY7R9OnTK73ugQMHKt2/YsUKERgY6L0/LCys0jGquH18fHylbQ8ePCjuvfdekZCQIAIDA4Xb7RYtW7YUAwcOFI888ojYtWuXEEKIK6+8slIN5/5X8XnPPbYfffSR6N+/vwgODvY+bsGCBZUeV1HF15o4caJIT08X48ePF1FRUSI4OFgkJyeLr7766rzjdO7rXug5qzquVf139lhXtX1Fqamp4r777vMex+DgYJGYmCgeeOCB896vqp4vNTVV3HTTTSIyMlIEBgaKAQMGiHXr1p23HVFNGMJUJ1OmTKn0offJJ5/U+Tn++te/Ck3Tqv0g7d+/v8jLy6u0TcX7Bw4cWOV2HTp0qBTg54bwoEGDKt0+++FcVFQkhg4desEP91mzZtV6/2oKYSGEeO211yo95qWXXqpy+4phmZWVJZo2bXrBOufOnSuEuPgQPvcY1TWEr7jiChEVFXXe62madt7viqwQXrx4caUvQef+FxYWJj7//PNq6+nRo4cIDQ09b7uAgADx448/VvEbQVQ9dkdTnaxdu9b778jISIwbN65O22/cuBEPPvigd7BWcnIyrr76auTl5WHRokU4efIkNm/ejKlTp+KDDz6o8jm+/vprdOvWDWPGjEFKSgrWr18PANi3bx+WLl2KW265pdrX7tGjB66//npYluU93/rwww9j3bp1AAC3241bb70V7du3x/bt2/Hvf/8bAPD000+jX79+GDFiRJ32tzqTJ0/GH/7wB+9xWLt2LZ544okLbvPJJ5/gxIkTAMqP/eTJkxEdHY0jR44gNTUVKSkp3seePSf62GOPeX82YcIE9OvXD0D155o3btyI2NhYTJgwAVFRUThw4ECd9uubb75By5Yt8fjjj6OgoADz5s1DaWkpTNPE3Xffjauvvhrh4eF1es6zzp4rnzt3Lvbv3w8A6NevX6Wu56ioqAs+R1paGu644w6UlpYCAJo2bYqJEyfCMAzMnz8f+fn5KCgowPjx47F3717Exsae9xw7d+5ETEwMpkyZgqysLPzjH/8AAJSVleGNN97AW2+9dVH7Rw4l+1sA+Zfg4GDvN//LLrus0n0HDhyosmXx61//2vuYcePGeX9+7bXXCsuyvPetWbPGe5+iKOLQoUPe+yo+X3x8vCgsLBRCCFFWViaaNWvmve/RRx/1bnNuS3jw4MGitLS0Us05OTmVWuUffPBBpftvvvlm733XXHNNrY5RbVrCQohKdXfp0qXK7Su2WP/yl794f37fffed93yFhYXi2LFjlX5WsY5zW5tVPaZJkybi8OHD5z2mti1hl8tVaX/ff//9StvNmzevVrVdqCVbU1fzhR7z0EMPeX+uqqq3+14IIdavX1+pphdeeKHK51NVVXz//ffe+8aOHeu9r0+fPlXWQ1QdTlGii3bufNHa2Lhxo/ffn3/+OVRV9U43ue6667z3CSGwadOmKp/jt7/9LUJCQgAALpcL7dq189538uTJal/70UcfRUBAQKWfffvttzBN03v71ltvrTSt56OPPvLe9/XXX9dyL2tH1HHq1qBBg7zH/O2330bfvn1x++2344UXXsCaNWug63qVLbe6mDhxIlq2bHnR2w8ePLjSSPgJEybA5XJ5b2/ZsuVSyrtkFd/Dfv36ISkpyXt78ODBlX6Xqnu/r7jiCvTo0cN7OzEx0fvvC/3+EVWFIUx10qpVK++/09LSKgVJVFQUZs+ejdmzZyMyMrLK7XNzc2v9Wme7Xs8VHx9f6bbb7fb+27Ksap+vU6dOl1RPUVFRvY32zs3NRXZ2tvd2xeNancsuuwx/+ctfEBoaCiEEtm3bhn/+85945plnMHLkSMTFxeH//u//Lqmuqo5RXTRr1qzSbU3TEB0d7b1dXUid+4XkbHdxfav4+ufWCqDSl5jqar3Y3z+iqvCcMNXJ8OHDkZaWBqA8SFasWIExY8YAAMLDw/GHP/wBAPC3v/2tyg+xyMhIb7gOHToUo0aNqva1rrjiiip/XrFlBdS+RR4cHFxlPRU99thjVX44n6Xr9fMns2DBgkrBM2zYsFpt9/DDD+Pee+/Fpk2b8NNPPyEtLQ1r1qxBWloasrOzMWnSJBw8ePCi66rqGNXF8ePHK902TRM5OTne202aNPH+W1EU7zGo+OXGsizvOd/6VvH9PrdWAMjKyqrysRVd7O8fUVUYwlQnv/vd7/DOO+94u3CnTJmCNm3aoHfv3rXafuDAgVi+fDkA4NixY5g6daq3a/ms/Px8rF69Gr169arX2qty+eWXQ9M07/4EBQV5v0hUtGvXLuTm5p73AXwxPv30U/zpT3/y3g4LC8Pdd99d43ZHjhyBpmmIjY3FsGHDvMG9fft29OnTBwCQkZGBnJwcb+tT13UYhgEAKC4uvuTaa5KSkoKDBw96u6QXL14Mj8fjvf/swDCgPJDPflH79ttvMW3aNADlS2RWFZBnVXwP6rpPAwcOxObNmwGUd43v3r3b2yWdkpJSaSCar8zVJntjCFOddO3aFc8//zyeeuopAOVB2r9/f1x33XXo27cv3G43MjIyKrUoKvr973+PFStWQAiB3bt3o1u3brjxxhsRExOD3Nxc7NixAykpKWjevHmjLLgQHR2NSZMmYd68eQCA5557Dps2bcKAAQPgcrnw888/Y+PGjdi1axemT5+O5OTkOr/GO++8g4iICGRnZ2P9+vXexTqA8lbUvHnzEBMTU+PzrF+/HrfddhuSk5ORlJSEli1bwjRN7whuAAgICEBQUJD3dqtWrZCRkQEAeO2115CTk4OgoCD07t0bw4cPr/O+1MTj8WDQoEG4/fbbvaOjz2rSpEmlRUn69euHL7/8EgDw3nvv4dixY3C5XFi9evUFX6Ni1/1nn32GJ554AjExMYiJialxGctp06Zh7ty5KCsrg2VZuPLKKyuNjj6rtl+MiC6ZvDFh5M/eeOONC861rPjfvffee962F5onDJy/SEXF+2o7kvbc0dHVjVIuLCyscZ4wADF9+vRaHZvazGcFIKKjo8WKFSsuuH3F4/Dhhx/W+JwVR4cLIcQjjzxS5ePuv//+Wh3bs2o7OrpPnz4iLCzsvNdTVVUsWbKk0nZr1qwRiqJU+d4nJiZWOwJ6+fLlVe5T165dq6zp3O0//PBD4Xa7qz2GISEhYtWqVdXu47nPd6HFVYhqwoFZdFEeeOABHDhwAM899xyGDBmCZs2aweVyISgoCK1bt8bVV1+NZ599Fps3bz5v3uQDDzyALVu24K677kJCQgICAwMREhKCjh074rrrrsOcOXO8c38bQ0hICP7zn//gvffew4gRI9C0aVO4XC7ExMSgZ8+emDRpEpYuXYrHH3/8ol9D13VERkaic+fOGDNmDN58801kZGSct270hSQnJ2PWrFm4/vrr0aFDB4SFhUHXdTRt2hTDhw/HwoUL8ec//7nSNrNmzcKDDz6IVq1aQdO0i66/trp3747vvvsO48aNQ2RkJIKCgjBo0CB8/vnnuOmmmyo99tprr8WSJUvQs2dPBAQEoFmzZrjnnnvw3XffoXnz5tW+xujRo/G3v/0NSUlJF3V64Oabb8b27dtxzz33oEOHDggMDERgYCA6deqE+++/Hzt37sTIkSPr/LxEF0MRwmGXuCEiIvIRbAkTERFJwhAmIiKShCFMREQkCUOYiIhIEoYwERGRJAxhIiIiSRjCREREkjCEiYiIJGEIExERScIQJiIikoQhTEREJAlDmIiISBKGMBERkSQMYSIiIkkYwkRERJIwhImIiCRhCBMREUnCECYiIpKEIUxERCQJQ5iIiEgShjAREZEkDGEiIiJJGMJERESSMISJiIgkYQgTERFJwhAmIiKShCFMREQkCUOYiIhIEoYwERGRJAxhIiIiSRjCREREkjCEiYiIJGEIExERScIQJiIikoQhTEREJAlDmIiISBKGMBERkSQMYSIiIkkYwkRERJIwhImIiCRhCBMREUnCECYiIpKEIUxERCQJQ5iIiEgShjAREZEkDGEiIiJJGMJERESSMISJiIgkYQgTERFJwhAmIiKShCFMREQkCUOYiIhIEoYwERGRJLrsAoiczLQETNOCqijQ9Qt/JzZMC6fLTJimgCUEhBCwRPl9qgIoigJVUaBpCgIDNOhaDc9nWLCEgKap0FSlvnaJiOqAIUzUQCxLwDAt6LoKVfkl5ErLTBzPK8HRnBJknihCVm4JjuYU43jeaRQUe1BU4kFhiQeFJUal/5d5rDq9foBLRWiQC6FBeqX/hwS5EBbsQrMmgWgRHYzYqCDENQ1Bi+ggNGsSBHeA9ss+CAHDsKBrKlQGNVG9U4QQQnYRRP7MY5hQ1V9ak4ZpIfNEEVIzTmHvoVNIP5yPA0cLcCS7GFm5Jcgv9kiu+MLCg12IjQpCy5hgtGsRho5x4egYF4HO8RGIaxribWGbloBlWXDpWg3PSETVYQgT1YHHsKBrChRFgcewsCsjD9v2ZHvDNj0zHxlZhTBMe/5Z6ZqC+NhQJMSFI6FVODq1jkCfxBh0iW8Cl65CCAHDFHDV0LVOROUYwkTVMAwL2pnALfOY2HUwD1tSs7E9PQc70nKwOyPPtmFbVy5dRec2EejVMRq9E6LRr3MMurRtggCXBiEETFPUeM6byIkYwkRnVAzd4ydLsHbbEWz4IQtb92Rjz8+nGLh1pGsKEttEoG9iDJK7x2JYn5ZoFhnEUCaqgCFMjmWYFjS1cuim7MzChp3HcOBooezybKldi1AM7tkcg3s0x9DeLX4JZUvUOJqbyI4YwuQoHsOCS1dRdNrAF5sz8dXWI9jwfRb2Hy2QXZojtW8RhuSesRjetyVG9I9DSKDufY+InIAhTLZWsZV1JLsYKzf+jFWbDmHDD1nwGHWb8kMNy6WrSO4ei1EDWmN0chu0iA6GcWYONadHkV0xhMl2rDMrWKiqgh3pOd7g/elAntzCqE66tmuCUQNa44ZBbdArIbrS+0pkFwxhsg3DLF9U4vv0XHz4n3349/qDOJZbIrssqgfNo4Jw45C2uOXqDuiZEOV9r4n8HUOY/NrZ84eZx4vw/pfpWLzuANIz82WXRQ2oY1w4Jgxrj1uv7oC4ZiE8h0x+jSFMfudsKyivsAxL1u3H4rX78d3ubNllkQSXJTXFhGHtMH5oezQJDWALmfwOQ5j8hmFaUFUFa7cewbzP9uLz7zI5d5cAlA/qGtG/Fe7+VSKG9mkBi1OeyE8whMmnmaYFTVORm1+K+av2YtHqNGRkcQ4vVS8+NhQTR3bEnaM6ISrc7f0dIvJFDGHySWfP823Zk425S3dj2YYMTimiOglwqRgzKB7TxiWhb2IMzx2TT2IIk08xzPKgXbLuAOYu240d6bmSKyI76N0xGlPGdMb4oe0AgF3V5DMYwuQTTNOCxxSY/9ke/PWTXTicXSy7JLKhVjHBeODXXXDX9YnQNYXd1CQdQ5ikEUJACKDotIG/L92FuctTkZtfKrsscoDoCDemjknC1LFJCAnUoSiAonAREGp8DGFqdJYloChA9qlSvL7kRyxYtReFJYbsssiBwoJdmDyqEx4e3xXR4W4IwRW5qHExhKnRCCEgABw/WYKX/7kT73+ZjlIPB1uRfG6XituuScATv+2BZk2C2DKmRsMQpkZhWhaKSgy88sFOvLNyD06XmbJLIjpPYICGe25IxOO39kBIoM5zxtTgGMLUoAzTgmkK/PXfuzBnyY84VeSRXRJRjSJCXHhofDc8cGMXaJrC0dTUYBjC1CA8RvnqVgtX78XL7+9EFi+kQH6oeVQQnritByaO7ATLEpxnTPWOIUz16uzavctSDmLmgu3Yd6RAdklEl6xDyzBMn9wbYwe35frUVK8YwlQvzg66Sjt0Cg//9Vts/CFLdklE9W5Q91jMeXAAEuLCoYCDt+jSMYTpkhmmhVKPhecXbsfbK1N5UQWyNV1TcN/ozvjTxN5wu1S2iumSMITpop3tllu8dj/+9O5WnvclR4mNCsKsu/viN8Pas4uaLhpDmC6KEAJ7D53CQ29swtc/HpddDpE0g7rH4vUHLkfH1hFQ2T1NdcQQpjrxGBYsS2Dmwu14c/ludj0TobyLesqYJEyf1JtTmqhOGMJUa0IIbE7Nxn2zN3DUM1EVOrQMw1uPJaN/5xgO2qJaYQhTjTyGBUsIzJi/DXOXp8Ky+CtDVB1VVTB1bGfMmNwHqqJwbjFdEEOYLkgIgS17ylu/6YfZ+iWqrYS4cLz9h0Hom8hWMVWPIUxVMgwLphCYsWAb5i5j65foYqiqgmljkzB9cm+2iqlKDGE6j2UJ/HjgJCa9tB7pmfmyyyHyewlx4Vj45BB0bRcJjZdKpAoYwuRlWQKqquB//70L0xdsQxkvM0hUbwJcKmZO7oP7b+zi/VsjYggTgPLBVyWlBu6ZvQGrN2XKLofItkYNaI23HxuEYLcOnd3TjscQJlhCYOuebEyctR6ZJ4pkl0Nke3FNQ7Do6SHomxjDBT4cjiHsYKYloKkK/vzRD3jxHzu48AZRI9I1BU/f0Qu/n9Dd+7dIzsMQdijDsFBQ4sGdL6fgq61HZJdD5FjD+7bE/CcGIyzIxe5pB2IIO5BpWkj9+RTGP7uW3c9EPiCuaQiWPDcMndtEQOOSl47CEHagZSkHMeXPX6O41JBdChGdEezW8dZjgzAmOV52KdSIGMIOcXZKxAvvbcerH/wguxwiqoKiAH+8pQeevqMXpzE5BEPYAQzTgsewcNcrKfj060OyyyGiGtwwqA3mPZ4MXVN5RSabYwjbnGFayDpZgpue+Qo/HciTXQ4R1VK3dpFY8vwwxEYGMYhtjCFsY6ZlYeueHEyYsRY5p0pll0NEdRQd4cbiGcPQNzGGU5hsiiFsU5YQWPNtJia9uB6ny0zZ5RDRRQoM0LDoqSG49vI4LuxhQwxhm1q0Og0P/3UTTF79iMjvaaqCOQ8NwB3XdpRdCtUzhrANvfrBTrzw3g7ZZRBRPXtmYi88dksP2WVQPWII24RlCUABHvv7d3hn5R7Z5RBRA7n3hkS8Ou0yQIBTmGyAIWwDpmXBsoC7XknBspQM2eUQUQMbNzge854YDEUBNJUjp/0ZQ9jPnZ0DPP7ZtVj//THZ5RBRI7myV3N8PHMYAnSVS136MYawHzNMC6UeC2Of+hLf7johuxwiamSXd2mK5S9eA7eLQeyvGMJ+yjAtlJaZGP3kl9icmi27HCKSpH/nGKx46Rq4AzQu6uGHGMJ+yDAtlJSauOGJL7Btb47scohIsj6dorHy5REIcjOI/Q1D2M+cbQFf/zgDmIh+0adTND57ZQRbxH6G75QfMc+cAx795JcMYCKqZNveHIx+8kuUeiyYpiW7HKolhrCfMK3yAB7Dc8BEVI3NqdkY+9SXKDMsmBaD2B8whP2AZQlYFvCb6Wvx3W6Ogiai6n276wTGP7sWQpxZxId8GkPYHyjA3a+kcB4wEdXK+u+P4a6XUwAuqOXzGMJ+4I9//w5LuRIWEdXB0pQMPD53s+wyqAYMYR/36gc78TbXgiaii/DWilTM/nCn7DLoAhjCPsoSAovWpPFqSER0SZ5ftAPvfZ4Gi7NRfRJD2AeZloU132bi4Tc2yS6FiGzgoTmb8Pm3mby+uA/iYh0+xjAtbNubg189/gVOl5myyyEimwgM0PDpKyPQp1M0F/PwIQxhH2KYFrJyS5D8u0+Rc6pUdjlEZDPREW5s+N9fITYyiEHsI/gu+AjLEvAYFm569isGMBE1iJxTpRj/zFp4DItziH0EQ9hHqKqCu15JwU8H8mSXQkQ29uOBk7j71Q1QVU4i9gUMYR/xwnvb8enXh2SXQUQOsHLjz5jFmRc+gSEsmWlaWJaSgVc/+EF2KUTkIK9+uBPLN2TwYg+ScWCWRB7Dwt5DpzD84dUoLjVkl0NEDhPs1rF2zkh0iouArrNNJgOPuiSmJVBY4sH4Z9cygIlIiuJSA+OfXYuCEg/nEEvCEJZEUxVMfmk9Mk8UyS6FiBzs0PEi3PlyCjQO1JKCISyBJQReW/wD1m47KrsUIiJ8tfUIXlv8A6ctScBzwo3MY1jYkZ6Da3+/BobJQ09EvkHXFHzx2nXolRDN88ONiEe6EVmWQEmpgYmz1jOAicinGKbAxBfXo7jUYIu4ETGEG5GqKrhn9gaeByYin3ToeBHunb2RC3k0IoZwIzEtgf/99y6s3pQpuxQiomqt2nQIf1+6i63hRsJzwo3AMCzsysjDsIdXoczDifFE5NsCXCrWvj4KSfFN4OL54QbFo9sITCEw6aX1DGAi8gtlHguTX1oPttEaHkO4gQkhMHPBdqRn5ssuhYio1tIy8zFz4XYGcQNjCDcgj2Fhy55s/H3ZbtmlEBHV2f8u3Y2te7JhGOzFaygM4QZkCYH7Zm/gAAci8kuWJXDv7A0w2RpuMAzhBiKEwIz525B+uEB2KUREFy39cAFmLNjGbukGwhBuAIZpYXNqNuYuT5VdChHRJZu7LBWbU7PhYbd0vWMINwDTZDc0EdmHZQlM+fMGWGwN1zuGcD2zhMDMhdux7wi7oYnIPtIPF2Dmgu0M4nrGEK5Hhmkh7dApzOVoaCKyoTeX70Z6Zj4Mk93S9YUhXI90TcVDb2zixbGJyJYMU+ChNzZB1xgd9YVHsp4YpoWP1+7H1z8el10KEVGD2fhDFpasO8DWcD1hCNcDIQRKPRaefner7FKIiBrc0+9sQSmX4a0XDOF6IAC8sGg7snJLZJdCRNTgjuWW4IX3OEirPjCEL9HZwVhvreCcYCJyjreWp3KQVj1gCF+is4OxDJPfCInIOThIq37w6F0Cj2FhWcpBDsYiIkfa+EMWlqUc5Epal4AhfAkUBZi5YLvsMoiIpHlu4XaoqiK7DL/FEL5Ihmlh0Zo0roxFRI6WfrgAi1bv5bnhi8QQvkimKfDy+ztll0FEJN3L7++EyXExF4UhfBFMy8Jf/72LU5KIiFA+ZelvS3dxtcCLwBCuIyEEikoMzFnyo+xSiIh8xusf/4iiEg+vO1xHDOE6EgBe+WAnThV5ZJdCROQzThV58OqHP4ARXDcM4TqwLIHjJ0vwNhfmICI6z9srUnH8ZAmvpV4HDOE6UBTg5X/u5JqpRERVOF1m4uV/7oTCGUu1xhCuJSEEcvJL8f6X6bJLISLyWe9/mY6c/FKeG64lhnAtCQG8vuQntoKJiC6g1GNhzpKfwAyuHYZwLRWdNjD/sz2yyyAi8nnzV+1F0WlDdhl+gSFcC6Zp4e9Ld6GwhL9UREQ1KSj2YO6y3TC5ilaNGMK14DEF5i7niGgiotqau3w3ry5XCwzhGhimhfmf7UFufqnsUoiI/EbOqVLMX8U1pWvCEK6Fv36yS3YJRER+h5+dNWMIX4DHsLBk3QEczi6WXQoRkd/JPFGEJesO8HrDF8AQvgCXrmLust2yyyAi8ltvLk+FS2fUVIdHphqmaWHLnmzsSM+VXQoRkd/anpaDrXuyOVK6GgzhamiairlL2QomIrpUc5fthqYxbqrCo1KN3PxSLNuQIbsMIiK/t2xDBmeYVIMhXAXDtDB/1V4OJiAiqgdlHgsLVnO6UlUYwlVQVQWLVqfJLoOIyDYWrU6DqvLySudiCJ/DMC2s3XoEGVmFskshIrKNg8cKsW7bUbaGz8EQPoeuqZj32V7ZZRAR2c67n+6BzgFalfBonCOvsAyff5cpuwwiItv5YvNh5BWWyS7DpzCEKyhfIWs/Fx0nImoAHsPCv7iCViUM4QpcuorFa/fLLoOIyLY+WrufK2hVwCNRwaHjhfhud7bsMoiIbOu73SeQebxIdhk+gyF8hmFa+ODLfbLLICKyvQ/+s4+jpM9gCJ+hayoWrzsguwwiIttbvHY/R0mfwaMAwLIEvk/PRXpmvuxSiIhsLy0zHzv35cKyOAiWIXzGh/9hVzQRUWPhZ245hjDKl6n89/qDsssgInKMT/57kMtYgiEMyxLYkZ6DY7klskshInKMY7kl+D6dXdIMYSGwcuPPsssgInKclV9nwBIMYUfTNRWrNh2SXQYRkeOs+ibT8aOknb33AI5kF+OnA3myyyAicpwfD5zE0Zxi2WVI5egQ9hgWu6KJiCRaufFnR68l7egQdunsiiYikmnVpkOOXkvauXsOoOi0gQ0/ZMkug4jIsTb8kIXi04bsMqRxbAgbpoUvNmc6uhuEiEi2Mo+FLzYfduxa0o4NYU1V8NXWI7LLICJyvK+2HnHswh2ODWFFUbDhe3ZFExHJtmHnMagKQ9hRjp8swf6jBbLLICJyvH1HCnAiz5mrFjoyhA3Dwtpt7IomIvIVa7cddeR5YUeGsKYpSNnJrmgiIl+RsvMYNAeeF3ZkCCuKgg07j8kug4iIztjwfRYUB54XdmQIZ+WW4MDRQtllEBHRGfuPFuD4SeedF3ZcCHsMC+u283wwEZGvWbf9KAyHrd3guBDWNYWrZBER+aANO7Ogac7qknZcCCuKgq17smWXQURE59i6J9tx54UdF8JlHhN7fj4luwwiIjpH6s95KPOYsstoVI4L4V0H82CYQnYZRER0DsMU2J2RJ7uMRuWoEPYYFraksiuaiMhXbU7NhsdwTmvYUSGsawq2p+fILoOIiKqxIz0HuuacaHLOnqJ8UNaONIYwEZGv2pGW66jBWY4KYY9hOe58AxGRP9mdkeeo67w7KoR3ZXBQFhGRL/MYFlId1FhyTAh7DBPbOD+YiMjnbdmT7ZjWsGNCWFVV7D3E+cFERL5ub+YpOOWCSo4JYU1VkH44X3YZRERUg32Z+dAcMkLaGXt5RnomQ5iIyNc5qcHkmBA2TAsZWbx8IRGRrzt4rBCmyXPCtpJ5oogjo4mI/IBhCmSeKJZdRqNwRAhblkBqBgdlERH5i9Sf82AJ+zecHBHChmlxZDQRkR/Ze+gUDAdMU3JECOu66qgT/URE/i79cD503f4RZf89BKAqCg4cLZBdBhER1dL+IwVQHbCGtCNCGACOZDvjJD8RkR0czSmRXUKjcEwIZ+U64w0lIrKDrFxnNJwcEcKlZSbyiz2yyyAiolo6VeRBqceUXUaDc0QIH89jK5iIyN+cyDstu4QG54gQdsq5BSIiOznqgLE8tg9h0xLIPFEkuwwiIqqjzOwimJa9F+ywfwibFgdlERH5oazcEtuvIW37EFYVBUdz7N+lQURkN0dzSqDYfK6w7UNY11Ucd8DJfSIiuzl+sgQum6+aZe+9O6OA05OIiPyOEz67HRHCRSX2fyOJiOym6LQhu4QG54gQLmQIExH5HbaEbaKwxP7fpoiI7KboNEPYFtgSJiLyP4XF9m9AOSSE7f9GEhHZTSFbwvbAljARkf8p5Dlh/2eYFso89l5xhYjIjko9FlfM8neny+x/KSwiIruy+2e47UPYNO29+DcRkZ3xAg5+zhL2fgOJiOzM7p/htg9hYfM3kIjIzmzeELZ/CNv9DSQisjO7N6RsH8JERES+yvYhrNr7UpRERLbG6wn7Obu/gUREdmb3hpTtQ1hlCBMR+S27f4bbPoQ1zd5vIBGRnWk2bwrbPoQDAzTZJRAR0UWy+2e47UNY11QEuGy/m0REtuN2qdA0e39+23vvzggNcskugYiI6ig02P6f3Q4JYV12CUREVEehgQxhW2BLmIjI/4QG278B5ZAQtv8bSURkNyFsCdsDW8JERP4njOeE7SGEIUxE5HdCAu3fi+mIEHbCtykiIrtxwme37UPYMCw0axIouwwiIqqjZpFB8BiW7DIalO1D2BICLaKDZZdBRER11CI6iNcT9neapiI2Kkh2GUREVEexUUHQuWKWf9NUBXFNQ2SXQUREdRQXEwKVF3Dwfy2i2RImIvI3LWLsfyrRESHcrAlDmIjI3zR1wKBaR4SwO0BDuAOGuhMR2UVEiAtul70vYwg4JIQBcHAWEZEfiY2yf1c04KAQbumAcwtERHbhlLE8jghhSwi0axEmuwwiIqql9i3DYNl8jjDgkBA2DAsJrcJll0FERLWU0Cochs1XywIcEsK6pqJT6wjZZRARUS11ah0BXbd/RNl/DwGoqoLO8QxhIiJ/0blNE6iKvRfqABwSwgAQ1zQEumb/N5SIyN/pmoK4ps4YTOuYENY1FfGxobLLICKiGrRtHgrN5mtGn+WMvTwjIY6Ds4iIfJ2TBtI6JoRNSzjqjSUi8lcd4sJhmvYfGQ04KIQty+IIaSIiP9ApLgKW/acIA3BQCLt0DX0SY2SXQURENeiXGAOXA6YnAQ4KYQDoEt+EI6SJiHyYS1fROb6J7DIajaNC2KWrSHLQm0tE5G+S4ps4phUMOCyEhRDo1TFadhlERFSNXh2jIBywZvRZjgphwxToncAQJiLyVb0SomE4ZGQ04LAQdukq+nXm4CwiIl/Vv3MMXLomu4xG46gQBoAubTk4i4jIF+ma4rhxO44L4QCXhsQ2nC9MRORrOrdpggCXc1rBgANDWAiBvpwvTETkc/omxjhqUBbgwBA2TIHk7rGyyyAionMk94iFaTKEbc2lqxjau6XsMoiI6BxDe7eA7qA5woADQxgAYqOC0K4FL2tIROQr2rcIQ7PIINllNDpHhrAQAsk9mssug4iIzkjuGeu488GAQ0PYNAUG9+B5YSIiXzG4R3OYTrl0UgWODGFdVzGsD88LExH5imF9WkDXnBdJztvjM5pFBqF9izDZZRAROV6HlmFo2sR554MBB4ewEALJPdklTUQkW3KP5rAceD4YcHAIm5bA8L7skiYikm1435awHHg+GHBwCOuaihH94xx13UoiIl8T4FIxon8rR54PBhwcwgAQEqhz9SwiIomSu8ciOFCXXYY0jg5hj2Fh1IDWsssgInKsUQNaw2M45/rB53J0CLt0FTcMaiO7DCIix7phUBtHnxZ07p6f0TImGF3bNZFdBhGR43RrF4kW0cGyy5DK8SFsmOySJiKSYdQVcTBM53ZFAwxhqIrCLmkiIgluGBgPVVFklyEVQ1hV0CshGs2jnLlaCxGRDM2jgtAzIQqqyhB2PMsSuHFIW9llEBE5xq+vbOvYBToqYgifccvVHWSXQETkGPzMLccQRnmXdM+EKCTEhcsuhYjI9jrGhaNHB3ZFAwxhL8O0MGFoO9llEBHZ3oRh7R0/KvoshvAZuqbi1mvYPUJE1NBuvbqDY9eKPhePQgWtm4XisqQY2WUQEdnWZUlNEdcsRHYZPoMhXIHHsDBhWHvZZRAR2dbNw9o7eq3oczGEK3DpKsYPbQ9d42ABIqL65tJV3DS0naPXij4Xj8Q5moQG4NrL4mSXQURkOyP6t0KT0ADZZfgUhvA5DNPCXdd3kl0GEZHt3P2rRI6KPgdD+By6pmJY35aIjw2VXQoRkW20bR6KoX1acFT0OXg0qmBZAhNHdpRdBhGRbUwc2ZHLVFaBIVwFXVNx56hOCHDx8BARXaoAl4rJIzuxFVwFHpFqRIW7MWZQvOwyiIj83tjkeESFu2WX4ZMYwtUwTQtTxyXJLoOIyO9NHZsEkwOyqsQQroamqeiXGINeCVGySyEi8lu9O0ajb2IMNHZFV4lH5QI8hoWpY9kaJiK6WFPGdOYKWRfAEL6A8hW02qFVTLDsUoiI/E5c0xCM5wpZF8QjUwsP/LqL7BKIiPwOPztrxhCuga6puPP6RI7sIyKqg+gIN+4cxWlJNeHRqQWXpmDqmM6yyyAi8htTxyTxYji1wBCuBU1TMW1cF4QFu2SXQkTk88KCXZg2LokjomuBR6iWQgJ1TB7FCzsQEdXkzlGdEOzWZZfhFxjCtaQowMPju8LNpSyJiKrldql4aHxXKOyJrhUmSi0pioLocDduuyZBdilERD7rtmsSEB3uhsIUrhWGcB0IATzx2x4IDNBkl0JE5HMCAzQ8+dueELxYUq0xhOtAVRU0iwzCPTckyi6FiMjn3Du6M5o2CYSqshVcW4oQ/M5SF0IIFBR70PWOT3CqyCO7HCIinxAR4sJP7/0aYcEudkXXAVvCdaQoCkKCdDw0vpvsUoiIfMbDv+mGkECdAVxHDOGLoKkqHrixC2KjgmSXQkQkXfOoIPxuXBfOC74IPGIXSdMUPHFbD9llEBFJ98RtPaBxdayLwhC+SLqmYtLITujQMkx2KURE0iS0CsPEkVwj+mLxqF0CyxKYPrm37DKIiKR5dlJvWBbH914shvAlcOkqxg5ui0HdY2WXQkTU6JJ7xGLs4La8XvAl4JG7RIZp4fUHLufVQojIUXRNwesPDIBhWrJL8WsM4Uukayo6to7AfaN5qUMico77xnRGQlw4zwVfIi7WUQ+EECguNdHrzqXIyi2RXQ4RUYNqHhWE7fPHISSQV0q6VPwKUw8URYHbpWLW3X1ll0JE1OBm3dOPV5SrJzyK9UTXVPxmWHsM7NZMdilERA1mUPdYjB/ajt3Q9YRHsR4ZpoU5Dw7gIC0isiVdUzDnQQ7Gqk8M4Xp0dpDWlDFJskshIqp3U8YkcTBWPePArAZQWmZiwJQV2HekQHYpRET1IqFVGL55czTcLl5PvT7x60wD0DQFbz2WzGtqEpEtqOqZzzReIaneMYQbgK6p6N85BlPHcO4wEfm/qWM7o19iDFfGagDsjm5ApR4TV0xZgfTD7JYmIv+UEBeOb+bewG7oBsKvNQ1IVdgtTUT+S1UVvP2HQdDYDd1gGMINyKWr6JcYg2ljOVqaiPzP/eOS0DcxBjq7oRsMu6MbQanHxBVTVyI9M192KdTIjNxUlB1cDSv/IERpHgJ7PQhX7C8rqwkhULZvGTyZ/wfhKYIW0QHuLrdDC4375TGWB6V7PoJxdBOEVQYtqgsCu0yEGhh1wdcu+/krlB1cBVF6CmpoS7g73wY9MvGX+w+sQtnB1QCAgHbXI6Dtdd77zLx9OL17EYIHzICi8APYiTqe6YYOYDd0g+JfVyNQFQULnxyCAC7z5jxmKbSw1nAn3V7l3eVBuAbupNvLA88dgZItsyGMX9YgL019H0bWVgT2nIbgy/4EmKUo2fY/EKL6BRM8R79Faer7CGh/A4KveA5ak0SUbH0NVklOeVkFh1CavhSBPaYisMcUlKb9C2ZBJgBAWAZO71qIwC6TGMAOFeBSseDJIVDYDd3g+BfWCFy6iq7tIjFzch/ZpVAj05v2hLvjTXDF9jvvPiEEPBmfI6D9aLhi+0ELi0Ng93sgzDJ4jm4qf4ynGJ7M9XAn3gI9uiu08HgEdr8PVsEhmDk/Vfu6ZRlr4IobgoC4q6CFtkRg0m1QA6PgOfQVAMAqOgI1rDX06C7Qo7tCDWsNq+hI+bYHV0OLTIQW0b4Bjgj5g+fu7INu7SI5GroR8Ag3Ek1VcP+NXTByQFzNDyZHECUnIMpOQY/p5v2ZorqgRybCzEsDAJj5BwFhVnqMGhgJNTTO+5jzntcyYOUfhBbdrdLPtehuMPPSy58jtDWsomOwSnJglWTDKjoGNTQOVlEWPIdT4O7463reW/IX11/RGtPGdeGA0kbC61A1IssSeOexZAyYshKZJ4pkl0OSidJTAAAlILzSzxV3uLfbWJSeAhQdiivkvMec3f685y0rAIQFNSDinG0iYGWXb6OFtoS7000o3vIqAMDdaTy00JYo3vwK3J0mwMj+EWX7lgKKVn4uOYpz3p2gdbMQvP1YMixLMIQbCVvCjUhVFQS5dSx6eggv8kC/OPe8mwCA2vx+1PCY855XVDrHF9B6GEIHv4LQwa8goPUweA6nQNEDoTVJwOmf5iOo14NwJ96K0zvnQlie2uwJ+TFdU7DoqSEIDNAYwI2IIdzIXLqKvokxePqOXrJLIckUd3lL9dwWrSjLh+IO/+UxwoDwVO45EaW/POa85w0IAxQVVmne+c8bUPU2VlkBSvcthzvpdlin9kENjoUa0hx6dBJgmbCKjl3MLpIfefqOXujTiatiNTYebQlURcHvJ3TH8L4tZZdCEilBTaEERMDI+dH7M2EZME7ugdakIwBAC28LKFqlx1ilebAKM72POe95VR1qeNvzBm6ZOT9Ba5JQ5Talqe8jIP5aqIFR5aOuhflLTcIELjASm/zf8L4t8fsJ3dkCloAhLIlpCcx/YjDimobU/GDyW8I4DTM/A2Z+RvntkhMw8zNgleRAURS44q9F2f5P4cnaArMgE6d/eAeKFgBXiwEAAMUVDFfckPJ5wjk/wczPwOmdb0ENaw0tuqv3dYo3v4KyjC+9twPir4Mn87/wZK6HWXgEp1Pfh3U6B67Ww86r0cj+EVZxFlxthgMAtIj2sIqOwjjxPcoOrYOiqFBDWjTkYSKJWjcLwfwnBsO0uGSEDFysQyLDsLDn0CkMf3g1iksN2eVQAzByd6Nk88vn/VxvmYyg7vf8sljHoXUQRjG0iPZwJ90BLazCYh1mGUr3Lobn6DeA6YEW3QWBSXdADYr2Pqbwv7+Hq1Uy3AnjvD8r+/krlB1YBVGaBzWsFdyJt543wEqYZSj6+hkE9ZwGLTz+l20z/w9laf8GVB2BXe6A3rRXPR4V8hXBbh1r54xEp7gIroolCUNYMtO08Ok3h3D7C/+VXQoROYiiAP/405W4fkBraBoDWBYeeck0TcWY5Hj88dbuskshIgf54y09MHpQPANYMh59H/GnO3rjVwNbyy6DiBzghkFtOEPDR7A72kdYlkCpx8Swh1fhpwN5ssshIpvq1i4Sa+eMQoCucjS0D2BL2EeoqgKXruJfzw9HdIRbdjlEZEMxEYH41/PDoWsKA9hHMIR9iK6piI0MwuIZwxAYwMuHEVH9CQzQ8NGMoWgWGQid54F9Bt8JH6NrKvomRmPRU0Og8ZsqEdUDTS1fkrJvYgwD2Mfw3fBBmqri2svj8PqDA2SXQkQ2MOehAbj28jh+sfdBDGEfpSoKJl7XEX/iCEYiugTPTOyFO67tCPXcC3qQT2AI+7g/3toD996QKLsMIvJD943ujMdu6SG7DLoAhrAfeHXaZRg3OL7mBxIRnXHjkLZ4ZWp/2WVQDRjC/kAA854YjCt7NZddCRH5gSt7Nce7jyefuTY1+TKGsB9QVQWKAnw8cxgu79JUdjlE5MMu79IUH88cBkXhXGB/wBD2E5qqwqWrWPbiNejfOUZ2OUTkgy5LisHyF69BgK5yJLSfYAj7EV1T4XapWPHSNejTKbrmDYjIMfp2isbyF6+B26Xyogx+hO+Un9E1Fe4ADStfHsEgJiIAQJ9O0Vjx8gi4AzQGsJ/hu+WHdE1FkFvDZ6+MYNc0kcNdlhSDz14ZgSC3xtWw/BDfMT91tkW84uURHKxF5FADujbDipdGIDCAAeyv+K75MV1TEXjmHPGQnpy+ROQkV/ZqjuUvXs1zwH6O1xO2AdOyYFnA3a+kYGlKhuxyiKiBjRscj3lPDIaiKBwF7ecYwjZhWQJQgD/+/Tu8vXKP7HKIqIHcN7pz+UpYApwHbAMMYRua/eFOPL9oh+wyiKiePTOxF9eCthmGsE2993kaHpqzCabFt5fI32mqgjkPDcAd13aUXQrVM4awTVlC4PNvMzHxxfU4XWbKLoeILlKQW8PCJ4fg2svjeDlCG2II25hpCWzdk40JM9Yi51Sp7HKIqI6iI9xYPGMY+naK5ghom2II25xhWsg6WYKbnvkKPx3Ik10OEdVSt3aRWPL8MMRGBnEOsI0xhB3AMC14DAt3v7oBKzf+LLscIqrB6EFt8O7jydA1lQFscwxhh7CEgKoomPXeDrz64U7wXSfyPYoCPH5rDzx1ey9YluAUJAdgCDvQ8g0ZuG/2RhSXGrJLIaIzgt063v7jIIweFC+7FGpEDGEHMk0LqT+fwvhn1yLzRJHscogcr3WzECx5bhgSW0dwAJbDMIQdyjAsFJR4cOfLKfhq6xHZ5RA51vC+LTH/icEIC3JB1xnATsMQdjDTEtBUBa8t/gGz3tsBw+SvAlFj0TUFf7qjNx6d0M37t0jOwxAmWKJ8PvHEWevZPU3UCFo3C8Gip4agT6cYDr5yOIYwAQA8hoWSUgP3zt6IVZsOyS6HyLZGDWiNtx8bhGC3zu5nYgjTL85Oifj70l14dv42lHks2SUR2UaAS8Vzd/bBtHFdOP2IvBjCdB7TEvjpwElMemk90jPzZZdD5Pc6xoVjwZND0K1dJMOXKmEIU5U8hgVLCMxcsB1/X7a7/HrFRFQnqqrg/nFJmD6pNxRFgYvdz3QOhjBdkBACW/Zk477ZG5B+uEB2OUR+IyEuHG//YRD6JsZA4dWPqBoMYarR2VbxjAXbMHdZKlvFRBegqgqmjU3C9Mm9oSkKB1/RBTGEqdaEENicmo0pf2armKgqCa3C8NZjyejH1i/VEkOY6qTiueI3l+/mAh9EKF94Y8qY8tavynO/VAcMYboolhBIO3QKD72xCV//eFx2OUTSDOoeizkPDkBCXDhUtn6pjhjCdNEM04Kuqfh47X48/e5WZOWWyC6JqNE0jwrCrHv6YfzQdt6/BaK6YgjTJTNMC6UeCy8s2o63VqSyi5psTdcU3DemM565ozcCXCrDly4JQ5jqjSUE0jPz8dAbm7DxhyzZ5RDVu+QesXj9AXY9U/1hCFO9OtsttyzlIJ5buJ2jqMkWElqF4dlJvTF2cFt2PVO9YghTg/AYFlRVwaLVe/Hy+ztxjOeLyQ81jwrCk7/tiTuu6wjLEhz1TPWOIUwNyjAtmKbA35buwusf/4hTRR7ZJRHVKCLEhYd/0w2/G9cFmqaw5UsNhiFMjcK0LBSVGHj1wx/w9opUnC4zZZdEdJ7AAA33ju6MP97SHSGBOjSGLzUwhjA1GiEEBIDjJ0vw8j934v0v01HKyyWSD3C7VNx2TQKe/G1PNG0SCEUBV7yiRsEQpkZnWQKKAuTkl+L1JT9h/md7UFhiyC6LHCgs2IU7R3XCQ+O7IjrcDSHASw1So2IIkzRCCAgBFJ02MHfZbsxdvhs5p0pll0UOEB3hxrSxSZgyJgkhgTpbviQNQ5h8gmlaMEyB+av24o1//YTD2cWySyIbimsaggd+3QV3juoEXVN4zpekYwiTTzHM8nPES9YdwJvLU7E9LUdyRWQHvTtGY8qYzhg/tB0AcLQz+QyGMPkkj2HBpavYuicbc5ftxtKUDHgMDuKi2gtwqRibHI9p45LQp1OM93eKyJcwhMmnmaYFTVORm1+KBav3YuGqNGRkFcoui3xY2+ahmDiyIyaP7ISocLf3d4jIFzGEyW8YZvkqXOu2HcW7n+7BF5sPs3VMAACXrmJE/1a454ZEXNW7BSxLsMuZ/AJDmPzO2bV78wrL8K91B/DR2v34bvcJ2WWRBJd3aYoJQ9tj/LB2iAgJ4LrO5HcYwuTXzp7nyzxehA/+sw+L1+5HWma+7LKoAXWMC8fNw9vjluEdENcshOd6ya8xhMk2zraCdu7LxYf/2YdP/nuQF46wieZRQfj1lW1xy9Ud0KNDFFu8ZBsMYbIdyyr/lVZVBd+n52Ll1xlY9U0mfjxwUnJlVBfd2kVi1BVxuGFgPHomRFV6X4nsgiFMtmZZApYoH6RzNKcYKzf+jFWbDmHDD1ko47rVPiXApSK5eyxGDWiN0YPaoHl0cPlgPEVh8JJtMYTJUc6ePyw+beCLzYfx1dYj2LDzGPYdKZBdmiN1aBmG5B7NMbxvS4zo3wrBgTrP8ZKjMITJsQzTgqYqUBQFx0+WYN32o0jZeQwbvs/C/qMM5YbQvkUYBvdsjsE9YzG0dws0bRIESwhOKSLHYggTnWEYFjStcihv2JmFrXuykfpzHgyTfyp1oWsKOrdpgr6JMUjuUR66zSKDIISAydAlAsAQJqpWxVAu85jYnZGHzanZ2JGegx1pudidkcfFQs5w6SqS4pugV8co9EqIRv/OMUiKb4IAl1YeuqaAzi5movMwhInqwGOY0DUViqLAY1hIzcjDlj3Z2Jt5Cvsy85F+OB8HjxXattWsawraNg9FQqtwdIgLR6e4CPRLjEHn+CZw6SqEEDBMCy5dk10qkV9gCBNdIo9RvpymdmYEr2layDxRjNSf87D30CmkH87H/iMFOJpTgqzcYpwq8kiu+MIiQlyIjQpGi+ggtG8Zho5xEegYF47ObZogrmmwdx1m0yo/l8tBVEQXjyFM1EAsIWAYFnRdhVrhgvGlHhMn8k7jaHYxMrOLkJVbgqM5JTh+sgQFxR4UnTbO/N+DwmIDhac9KCz2oLSOU6rcLhWhwS6EBroQGqwjJNCFsGAXQgJ1hAW70CwyCC2igxAbFYS4mBC0iAlG0yaBcLt+acVWtw9EVD8YwkQSmZaAaVpQFKXGFqVpWjhdZpa3QIWAJQBxZgELRVWgKoCqlLfIAwO0Gq8c5DEsCCGgaaq3FU9EjYshTEREJAlP5hAREUnCECYiIpKEIUxERCQJQ5iIiEgShjAREZEkDGEiIiJJGMJERESSMISJiIgkYQgTERFJwhAmIiKShCFMREQkCUOYiIhIEoYwUQOZNGkSFEWBoijQdR1t2rTB1KlTcfLkSdmlEZGPYAgTNaDrrrsOR48excGDB/Huu+9i5cqVmDZtmuyyiMhHMISJGpDb7Ubz5s0RFxeHESNGYMKECfjiiy8AAKZp4q677kK7du0QFBSExMREzJkzp9L2kyZNwtixYzFz5kw0a9YM4eHhuO+++1BWViZjd4ionumyCyByiv3792PNmjVwuVwAAMuyEBcXh48//hgxMTH4+uuvce+996JFixb4zW9+493uq6++QmBgINatW4eDBw9i8uTJiImJwaxZs2TtChHVE0UIIWQXQWRHkyZNwj//+U8EBgbCNE2cPn0aAPCXv/wFjzzySJXb3H///cjKysK//vUv73OsXLkShw4dQnBwMADgzTffxGOPPYZTp05BVdmZReTP2BImakBDhw7F3LlzUVxcjHfffRd79+7FAw884L3/zTffxLvvvouMjAyUlJSgrKwMvXr1qvQcPXv29AYwAFxxxRUoLCzEoUOHEB8f31i7QkQNgF+jiRpQSEgIEhIS0KNHD7zxxhsoLS3FzJkzAQAff/wxHnnkEdx555344osvsGPHDkyePLnW53sVRWnI0omoEbAlTNSIpk+fjpEjR2Lq1KlISUnBwIEDK42W3rdv33nbfP/99ygpKUFQUBAAYNOmTQgNDUVcXFyj1U1EDYMtYaJGdNVVV6Fr16548cUXkZCQgC1btuDzzz/H3r178cwzz2Dz5s3nbVNWVoa77roLu3btwurVqzF9+nT87ne/4/lgIhtgS5iokT366KOYPHky9u7dix07dmDChAlQFAW33HILpk2bhtWrV1d6/PDhw9GxY0cMGTIEpaWluPnmmzFjxgw5xRNRveLoaCIfNmnSJOTl5WHZsmWySyGiBsD+LCIiIkkYwkRERJKwO5qIiEgStoSJiIgkYQgTERFJwhAmIiKShCFMREQkCUOYiIhIEoYwERGRJAxhIiIiSRjCREREkjCEiYiIJGEIExERScIQJiIikoQhTEREJAlDmIiISBKGMBERkSQMYSIiIkkYwkRERJIwhImIiCRhCBMREUnCECYiIpKEIUxERCQJQ5iIiEgShjAREZEkDGEiIiJJGMJERESSMISJiIgkYQgTERFJwhAmIiKShCFMREQkCUOYiIhIkv8HIEiCRDlMlZ4AAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 600x600 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler, MinMaxScaler\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Song Recommender\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"AI Song Recommendation System\")\n",
    "\n",
    "\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    ULH = pd.read_csv(\"User_Listening_History.csv\")\n",
    "    MI_info = pd.read_csv(\"Music_Info.csv\")\n",
    "    return ULH, MI_info\n",
    "\n",
    "\n",
    "ULH, MI_info = load_data()\n",
    "\n",
    "\n",
    "@st.cache_resource\n",
    "def build_model(MI_info, ULH):\n",
    "    song_data = MI_info.copy()\n",
    "\n",
    "    audio_features = [\n",
    "        \"danceability\", \"energy\", \"valence\", \"tempo\",\n",
    "        \"acousticness\", \"instrumentalness\",\n",
    "        \"liveness\", \"speechiness\", \"loudness\"\n",
    "    ]\n",
    "\n",
    "    song_data = song_data.dropna(subset=audio_features)\n",
    "    song_data = song_data.drop_duplicates(subset=[\"track_id\"])\n",
    "    song_data = song_data.reset_index(drop=True)\n",
    "\n",
    "    song_data[\"tags\"] = song_data[\"tags\"].fillna(\"\")\n",
    "    song_data[\"genre\"] = song_data[\"genre\"].fillna(\"\")\n",
    "    song_data[\"artist\"] = song_data[\"artist\"].fillna(\"\")\n",
    "    song_data[\"name\"] = song_data[\"name\"].fillna(\"\")\n",
    "    song_data[\"spotify_preview_url\"] = song_data[\"spotify_preview_url\"].fillna(\"\")\n",
    "\n",
    "    scaler = StandardScaler()\n",
    "    audio_scaled = scaler.fit_transform(song_data[audio_features])\n",
    "\n",
    "    song_data[\"text_features\"] = (\n",
    "        song_data[\"tags\"] + \" \" +\n",
    "        song_data[\"genre\"] + \" \" +\n",
    "        song_data[\"artist\"]\n",
    "    )\n",
    "\n",
    "    tfidf = TfidfVectorizer(stop_words=\"english\", max_features=5000)\n",
    "    text_matrix = tfidf.fit_transform(song_data[\"text_features\"])\n",
    "\n",
    "    listening_data = ULH.merge(\n",
    "        song_data[[\"track_id\"]],\n",
    "        on=\"track_id\",\n",
    "        how=\"inner\"\n",
    "    )\n",
    "\n",
    "    song_popularity = (\n",
    "        listening_data.groupby(\"track_id\")[\"playcount\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "    )\n",
    "\n",
    "    song_data = song_data.merge(song_popularity, on=\"track_id\", how=\"left\")\n",
    "    song_data[\"playcount\"] = song_data[\"playcount\"].fillna(0)\n",
    "\n",
    "    pop_scaler = MinMaxScaler()\n",
    "    song_data[\"popularity_score\"] = pop_scaler.fit_transform(\n",
    "        song_data[[\"playcount\"]]\n",
    "    )\n",
    "\n",
    "    return song_data, audio_scaled, text_matrix\n",
    "\n",
    "\n",
    "song_data, audio_scaled, text_matrix = build_model(MI_info, ULH)\n",
    "\n",
    "\n",
    "def hybrid_recommend(song_name, limit=10, exclude_same_artist=True):\n",
    "    matches = song_data[\n",
    "        song_data[\"name\"].str.lower().str.contains(song_name.lower(), na=False)\n",
    "    ]\n",
    "\n",
    "    if matches.empty:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    idx = matches.index[0]\n",
    "\n",
    "    audio_scores = cosine_similarity(\n",
    "        audio_scaled[idx].reshape(1, -1),\n",
    "        audio_scaled\n",
    "    )[0]\n",
    "\n",
    "    text_scores = cosine_similarity(\n",
    "        text_matrix[idx],\n",
    "        text_matrix\n",
    "    )[0]\n",
    "\n",
    "    pop_scores = song_data[\"popularity_score\"].values\n",
    "\n",
    "    final_scores = (\n",
    "        0.4 * audio_scores +\n",
    "        0.5 * text_scores +\n",
    "        0.1 * pop_scores\n",
    "    )\n",
    "\n",
    "    final_scores[idx] = -1\n",
    "\n",
    "    results = song_data.copy()\n",
    "    results[\"score\"] = final_scores\n",
    "\n",
    "    selected_artist = song_data.iloc[idx][\"artist\"]\n",
    "\n",
    "    if exclude_same_artist:\n",
    "        results = results[results[\"artist\"] != selected_artist]\n",
    "\n",
    "    return results.sort_values(\"score\", ascending=False).head(limit)\n",
    "\n",
    "\n",
    "def recommend_by_user(user_id, limit=10):\n",
    "    history = ULH[ULH[\"user_id\"] == user_id]\n",
    "\n",
    "    if history.empty:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    top_tracks = (\n",
    "        history.sort_values(\"playcount\", ascending=False)\n",
    "        .head(5)[\"track_id\"]\n",
    "    )\n",
    "\n",
    "    all_recs = []\n",
    "\n",
    "    for track_id in top_tracks:\n",
    "        song = song_data[song_data[\"track_id\"] == track_id]\n",
    "\n",
    "        if not song.empty:\n",
    "            recs = hybrid_recommend(\n",
    "                song.iloc[0][\"name\"],\n",
    "                limit=limit,\n",
    "                exclude_same_artist=True\n",
    "            )\n",
    "\n",
    "            if not recs.empty:\n",
    "                all_recs.append(recs)\n",
    "\n",
    "    if not all_recs:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    final = pd.concat(all_recs)\n",
    "\n",
    "    listened_tracks = history[\"track_id\"].tolist()\n",
    "    final = final[~final[\"track_id\"].isin(listened_tracks)]\n",
    "\n",
    "    final = final.drop_duplicates(subset=[\"track_id\"])\n",
    "    final = final.sort_values(\"score\", ascending=False)\n",
    "\n",
    "    return final.head(limit)\n",
    "\n",
    "\n",
    "def recommend_by_genre(genre, limit=10):\n",
    "    genre = genre.strip().lower()\n",
    "\n",
    "    result = song_data[\n",
    "        song_data[\"genre\"].str.lower().eq(genre)\n",
    "    ].copy()\n",
    "\n",
    "    if result.empty:\n",
    "        result = song_data[\n",
    "            song_data[\"tags\"].str.lower().str.contains(\n",
    "                rf\"\\b{genre}\\b\",\n",
    "                na=False,\n",
    "                regex=True\n",
    "            )\n",
    "        ].copy()\n",
    "\n",
    "    if result.empty:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    result = result.sort_values(\n",
    "        [\"popularity_score\", \"playcount\"],\n",
    "        ascending=False\n",
    "    ).head(limit)\n",
    "\n",
    "    result[\"score\"] = result[\"popularity_score\"]\n",
    "\n",
    "    return result\n",
    "\n",
    "\n",
    "def clean_display_table(df):\n",
    "    if df.empty:\n",
    "        return df\n",
    "\n",
    "    display_df = df.copy()\n",
    "\n",
    "    def get_genre(row):\n",
    "        if pd.notna(row[\"genre\"]) and str(row[\"genre\"]).strip() != \"\":\n",
    "            return row[\"genre\"]\n",
    "\n",
    "        tags = str(row[\"tags\"]).split(\",\")\n",
    "        if len(tags) > 0 and tags[0].strip() != \"\":\n",
    "            return tags[0].strip()\n",
    "\n",
    "        return \"Unknown\"\n",
    "\n",
    "    display_df[\"Genre\"] = display_df.apply(get_genre, axis=1)\n",
    "\n",
    "    display_df[\"Song\"] = display_df.apply(\n",
    "        lambda x: f'<a href=\"{x[\"spotify_preview_url\"]}\" target=\"_blank\">{x[\"name\"]}</a>'\n",
    "        if str(x[\"spotify_preview_url\"]).strip() != \"\"\n",
    "        else x[\"name\"],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "    display_df[\"Match Score\"] = display_df[\"score\"].round(3)\n",
    "\n",
    "    return display_df[[\"Song\", \"artist\", \"Genre\", \"Match Score\"]].rename(\n",
    "        columns={\"artist\": \"Artist\"}\n",
    "    )\n",
    "\n",
    "\n",
    "user_ids = sorted(ULH[\"user_id\"].unique())\n",
    "\n",
    "user_id = st.selectbox(\"Select User ID\", user_ids)\n",
    "\n",
    "user_history = ULH[ULH[\"user_id\"] == user_id]\n",
    "\n",
    "if not user_history.empty:\n",
    "    st.subheader(f\"Welcome {user_id}!\")\n",
    "\n",
    "    user_music = user_history.merge(MI_info, on=\"track_id\", how=\"left\")\n",
    "\n",
    "    user_music[\"genre_clean\"] = user_music[\"genre\"]\n",
    "\n",
    "    user_music[\"genre_clean\"] = user_music.apply(\n",
    "        lambda row: str(row[\"tags\"]).split(\",\")[0].strip()\n",
    "        if pd.isna(row[\"genre_clean\"]) or str(row[\"genre_clean\"]).strip() == \"\"\n",
    "        else row[\"genre_clean\"],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "        st.markdown(\"### Your Listening Genres\")\n",
    "\n",
    "        genre_counts = (\n",
    "            user_music.drop_duplicates(subset=[\"track_id\"])\n",
    "            [\"genre_clean\"]\n",
    "            .value_counts()\n",
    "            .head(6)\n",
    "        )\n",
    "\n",
    "        blue_colors = [\n",
    "            \"#0D47A1\", \"#1565C0\", \"#1976D2\",\n",
    "            \"#1E88E5\", \"#42A5F5\", \"#90CAF9\"\n",
    "        ]\n",
    "\n",
    "        fig, ax = plt.subplots(figsize=(6, 6))\n",
    "        ax.pie(\n",
    "            genre_counts,\n",
    "            labels=genre_counts.index,\n",
    "            autopct=\"%1.1f%%\",\n",
    "            startangle=90,\n",
    "            colors=blue_colors,\n",
    "            wedgeprops={\"edgecolor\": \"white\", \"linewidth\": 1}\n",
    "        )\n",
    "        ax.set_title(\"Genre Distribution\", fontsize=14, fontweight=\"bold\")\n",
    "        st.pyplot(fig)\n",
    "\n",
    "    with col2:\n",
    "        st.markdown(\"### Your Top Artists\")\n",
    "\n",
    "        top_artists = (\n",
    "            user_music.groupby(\"artist\")\n",
    "            .agg(\n",
    "                Songs=(\"track_id\", \"nunique\"),\n",
    "                Plays=(\"playcount\", \"sum\")\n",
    "            )\n",
    "            .reset_index()\n",
    "            .sort_values([\"Plays\", \"Songs\"], ascending=False)\n",
    "            .head(3)\n",
    "        )\n",
    "\n",
    "        st.dataframe(\n",
    "            top_artists[[\"artist\"]].rename(columns={\"artist\": \"Top Artists\"}),\n",
    "            hide_index=True,\n",
    "            use_container_width=True\n",
    "        )\n",
    "\n",
    "    st.divider()\n",
    "\n",
    "    st.subheader(\"Get Recommendations\")\n",
    "\n",
    "    mode = st.radio(\n",
    "        \"Choose recommendation type\",\n",
    "        [\n",
    "            \"Based on your music taste\",\n",
    "            \"Based on genre\",\n",
    "            \"Based on a song\"\n",
    "        ]\n",
    "    )\n",
    "\n",
    "    limit = st.slider(\"Number of recommendations\", 5, 25, 10)\n",
    "\n",
    "    if mode == \"Based on genre\":\n",
    "        genre = st.text_input(\"Enter genre or tag\", value=\"pop\")\n",
    "\n",
    "    if mode == \"Based on a song\":\n",
    "        song = st.text_input(\"Enter song name\", value=\"Creep\")\n",
    "\n",
    "    if st.button(\"Recommend\"):\n",
    "        if mode == \"Based on your music taste\":\n",
    "            result = recommend_by_user(user_id, limit)\n",
    "\n",
    "        elif mode == \"Based on genre\":\n",
    "            result = recommend_by_genre(genre, limit)\n",
    "\n",
    "        else:\n",
    "            result = hybrid_recommend(song, limit, exclude_same_artist=True)\n",
    "\n",
    "        if result.empty:\n",
    "            st.warning(\"No recommendations found.\")\n",
    "        else:\n",
    "            table = clean_display_table(result)\n",
    "            st.markdown(\n",
    "                table.to_html(escape=False, index=False),\n",
    "                unsafe_allow_html=True\n",
    "            )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
